### ISSUE TITLE
FontAwesome for ReactXP

### ISSUE THREAD

**Issue by mghazanfar** [Microsoft/reactxp#217] opened 2017-08-22 11:16 UTC
I am unable to use font awesome's npm library for react and react native on reactXp as no package is there for reactXP. Please guide me how can I use font awesome as components in reactXp. Please respond ASAP! below is my code that I am using:

import RX = require('reactxp');
import Avatar = require('./Avatar');
import Icon = require ('react-native-fa-icons');

interface PostCardProps {
  img?: string;
  titleName?: string;
  titleLine?: string;
  subTitle?: string;
}

class PostCard extends RX.Component<PostCardProps, null> {

    render() {
      const styles = {

          container: RX.Styles.createViewStyle({
              flex:1,
              padding: 20,
          }),
          postCard: RX.Styles.createViewStyle({
              shadowRadius: 5,
              shadowColor: 'black',
              elevation: 10,
              borderRadius: 5,
              flexDirection: 'row',
              marginVertical: 6,
              marginHorizontal: 12,
              backgroundColor: '#fff',
              justifyContent: 'space-between'
          }),
          btnText: RX.Styles.createTextStyle({
            fontWeight: 'bold'
          }),
          textMuted: RX.Styles.createTextStyle({
            color: 'grey'
          }),
          textPrimary: RX.Styles.createTextStyle({
            color: '#001dff'
          }),
          btnGroup1: RX.Styles.createViewStyle({
            flexDirection:'row',
            alignItems:'center',
            display:'block',
            marginTop: 10
          }),
          btnGroup2: RX.Styles.createViewStyle({
            flexDirection:'row',
            alignItems:'center',
            display:'block',
            marginTop: 5
          }),
          img: RX.Styles.createViewStyle({
            width:70,
            height:70
          }),
          dBox: RX.Styles.createViewStyle({
            display: '-webkit-box'
          }),
          imgContainer: RX.Styles.createViewStyle({
            flexDirection:'row',
          })
      };

        return (
          <RX.View style={ styles.container }>
            <RX.View style={styles.postCard }>
              <RX.View style={styles.dBox}>
                <Avatar src={this.props.img} size={50} noShade={true}/>
                <RX.View>
                <RX.View style={ styles.btnGroup1 }>
                  <RX.Link style={ styles.btnText }>{this.props.titleName}</RX.Link>
                  <RX.Text > {this.props.titleLine}</RX.Text>
                </RX.View>
                <RX.View style={ styles.btnGroup2 }>
                  <RX.Link style={styles.textPrimary}><Icon name='user' allowFontScaling /> {this.props.subTitle}</RX.Link>
                  <RX.Text style={ styles.textMuted }> . Web App</RX.Text>
                </RX.View>
                </RX.View>
              </RX.View>
              <RX.View>
                <RX.Link style={ styles.btnText }>{this.props.titleName}</RX.Link>
              </RX.View>
            </RX.View>
        </RX.View>
        );
    }

}

export = PostCard;

**Comment by waheed25** [comment] 2017-08-22 12:55
i want to use icons in my app is there any specific library that i can use or i have to use third party library ???

**Comment by ms-deregtd** [comment] 2017-08-22 16:30
Dupe of #218 .  See comment there about reactxp extensions.  Anything that's rn-only or react-only you need to wrap in a cross-platform reactxp extension before you can use with reactxp.

**Closed by ms-deregtd** 2017-08-22 16:30 UTC
