### ISSUE TITLE
ReactXP with React Hooks

### ISSUE THREAD

**Issue by ravilution** [Microsoft/reactxp#1025] opened 2019-02-08 14:54 UTC
I am going to start working with ReactXP for its great cross platform benefits. Can you confirm if it will work well with **React Hooks** and Classless/Functional Components?

**Comment by mikehardy** [comment] 2019-02-08 15:27
I must admit after reading the full React 16.8 release notes and Hooks tutorial I was curious as well. The release notes for React state that react-native won't have hooks until 0.60.0 but on their release discussions I think it's actually going to land in 0.59.0 which will be branched as soon as their done syncing with React 16.8 and confirm their CI works, so we should be able to test it shortly.

I can confirm in my project at least that with RN 0.58.4 and React (plus it's related modules) 16.8.1 everything appears to be working well, but I have not attempted to use hooks at all

**Comment by erictraut** [comment] 2019-02-08 16:23
I've read about React hooks, but I haven't started to use them. I didn't see anything in the hooks documentation that leads me to believe that ReactXP would be incompatible with them. I can confirm that ReactXP works fine for classless/functional components.

**Comment by ravilution** [comment] 2019-02-08 18:08
Steps for [Using React Hooks in React Native](https://github.com/facebook/react-native/issues/21967#issuecomment-434113687). We will have to try and create an **example**.

**Comment by mikehardy** [comment] 2019-02-09 16:47
I think @erictraut confirmed all that's needed. We just need to wait for the first 0.59rc for an easy test + example as they just committed react 16.8.1 into react-native master but haven't set a 0.59.x tag yet. Maybe worth leaving this open for full confirmation over the next couple days but it's probably not actionable for the reactxp repo

**Comment by dagatsoin** [comment] 2019-02-12 10:42
Indeed, I think the concern is more about the breaking changes introduces in 0.58 like in ScrollView, rather than hook. Do you think [that](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#breaking-changes) may break ?

**Comment by erictraut** [comment] 2019-02-12 14:03
Those changes shouldn't break ReactXP. We don't use any of these callbacks in an unbound form.

**Comment by mikehardy** [comment] 2019-02-12 14:22
That is also good news - I was curious about that but not familiar with the codebase and whether it uses bound or unbound this.

For those playing along at home the discussion on tagging 0.59.x indicated yesterday that there will be a 0.59.x tag "mid-week", so if you are really antsy to test it plus ReactXP, just a couple days more

**Comment by erictraut** [comment] 2019-02-12 14:50
If you do run into problems with the new React, let me know, and we can do a quick rev of ReactXP. It's been a couple of months since the last major release of ReactXP, and a number of (small) changes have been added since then, so it's about time that we release an update.

**Closed** 2019-02-17 19:04 UTC
