### ISSUE TITLE
Deprecated RN network event

### ISSUE THREAD

**Issue by nateabele** [Microsoft/reactxp#660] opened 2018-06-05 02:47 UTC
Getting the following warning on React Native 0.55:

```
NetInfo's "change" event is deprecated. Listen to the "connectionChange" event instead.
- node_modules/expo/src/Expo.js:21:41 in warn
- node_modules/react-native/Libraries/Network/NetInfo.js:108:19 in addEventListener
- node_modules/react-native/Libraries/Network/NetInfo.js:216:8 in addEventListener
- node_modules/reactxp/dist/native-common/Network.js:30:48 in Network
- node_modules/reactxp/dist/native-common/Network.js:98:18 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:214:12 in loadModuleImplementation
- node_modules/reactxp/dist/ios/ReactXP.js:31:16 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:214:12 in loadModuleImplementation
- node_modules/reactxp/index.ios.js:3:17 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:214:12 in loadModuleImplementation
* src/app.tsx:1:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:214:12 in loadModuleImplementation
* App.tsx:7:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:214:12 in loadModuleImplementation
- node_modules/react-native-scripts/build/bin/crna-entry.js:7:11 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:214:12 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:141:45 in guardedLoadModule
* null:null in global code
```

Looks like [this line](https://github.com/Microsoft/reactxp/blob/b09745b843dab1a3962ebfee0ee6fad51a7dcee0/src/native-common/Network.ts#L22) just needs a `s/change/connectionChange/`. I'll submit a PR if I have a moment.

**Comment by erictraut** [comment] 2018-06-10 17:27
This is a duplicate of #667.

**Closed by erictraut** 2018-06-10 17:27 UTC
