### ISSUE TITLE
React Native Upgrade?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#258] opened 2017-09-08 02:24 UTC
I use RN's FlatList in some mobile files, which does not exist in the current ReactXP version. I've been having an extremely hard time upgrading react native (endless npm errors all day), some of which are peer dependency issues of ReactXP's RN version.

I was wondering if ReactXP can upgrade to use a higher version of RN?

**Comment by erictraut** [comment] 2017-09-08 04:19
We are working to upgrade to version 0.46 of RN. We've taken the first step of removing our RX.Navigator to an extension. If you switch to ReactXP version 0.46.0_rc.2, you should be able to work fine with 0.46 of RN. There might be additional breaking changes on the 0.46 branch before we remove the "rc" moniker, but I'm hopeful that we'll get that done within the next week and release an official "0.46.0".

**Comment by erictraut** [comment] 2017-09-08 04:20
This is a duplicate of https://github.com/Microsoft/reactxp/issues/216, so closing.

**Closed by erictraut** 2017-09-08 04:20 UTC

**Comment by MovingGifts** [comment] 2017-09-08 14:28
Thank you :)
