### ISSUE TITLE
Navigator does not update background scenes on Android

### ISSUE THREAD

**Issue by a-s-o** [microsoft/reactxp#387] opened 2017-12-15 15:04 UTC
Hi,

I have run into an issue with the navigator where going back to a previous screen having updated the state does not reflect the changes on the previous screen. I.e. the previous screen is stale and not re-rendered. It works fine on the web and the issue is only on Android (I am not yet setup to test on iOS).

My actual use case is for a page with list of things which when clicked show details of a particular item. Then there is a button on the details page to delete the item which on press triggers a prop method. The prop method emits an event to delete the item and also navigates back to the list as a side effect. I do the state change asynchronously so during the back animation the item detail page does not error out (due to missing item). However, __after the navigation back the list screen should then update once the state is changed. This is not happening__. Neither `setState` nor `forceUpdate` re-render the list screen which is the expected behavior.

I have created an isolated example that is a simple counter to illustrate the problem. Here is the basic flow:

Code for the example is at https://gist.github.com/a-s-o/e6424ba1fc0527daaf35e391ec01b074

## Initial load

![screenshot_1513349138](https://user-images.githubusercontent.com/6897926/34047656-f372ae4c-e17e-11e7-8eb2-37fee069854e.png)

## Navigate to second page and click emit event button

![screenshot_1513349143](https://user-images.githubusercontent.com/6897926/34047678-036a3770-e17f-11e7-98f0-66e401042943.png)

## Show first page again (but problem: state has not updated!)

![screenshot_1513349147](https://user-images.githubusercontent.com/6897926/34047704-147ffad6-e17f-11e7-98cd-c8db093ae707.png)

On the web, this works just fine. The problem is only on Android. Additionally, we can be sure that the state updated because if I go back to page 2 it shows the correct counter value of `1`

Thanks in advance; any help is very much appreciated.

**Comment by a-s-o** [comment] 2017-12-15 15:08
In the example above actually looks like page 1 never updates and always shows a counter value of `0`; this is definitely wrong. Do we need a `rerenderRoute()` type method?

I presume that is not idiomatic React and the re-render should take place in response to `setState` or `forceUpdate`

**Comment by amandeepothi** [comment] 2018-01-04 13:04
Hello, just jumping back to share my current workaround for this issue just in case someone else need it. I have noticed that recreating the route manually will refresh it's state so I am doing that as follows. 

I have a wrapper class which wraps the navigator and has a `navigateTo(routeName, params)` method. I conditionally refresh() the route each time I do anything other than a `push`. Here is the abbreviated version:

```typescript
class MyWrapper {
  navigateTo(targetRouteId: number) {
    const currentIndex = this.navigator.getCurrentRoutes().findIndex(route => route.routeId === targetRouteId)

    if (currentIndex > -1) {
      const currentRoute = this.navigator.getCurrentRoutes()[currentIndex]
      this.navigator.popToRoute(currentRoute)
      this.refresh()  // FIXME: Workaround for https://github.com/Microsoft/reactxp/issues/387
    } else {
      this.navigator.push({
        targetRouteId,
        sceneConfigType: Types.NavigatorSceneConfigType.FloatFromRight
      })
    }
  }

  private refresh() {
    const routes = this.navigator.getCurrentRoutes()
    const index = routes.length - 1
    if (index >= 0) {
      const { routeId, sceneConfigType } = routes[index]
      this.navigator.replaceAtIndex({ routeId, sceneConfigType }, index)
    }
  }
}
```

Regards, Amandeep

**Comment by a-s-o** [comment] 2018-01-04 13:04
Hello, just jumping back to share my current workaround for this issue just in case someone else need it. I have noticed that recreating the route manually will refresh it's state so I am doing that as follows. 

I have a wrapper class which wraps the navigator and has a `navigateTo(routeName, params)` method. I conditionally refresh() the route each time I do anything other than a `push`. Here is the abbreviated version:

```typescript
class MyWrapper {
  navigateTo(targetRouteId: number) {
    const currentIndex = this.navigator.getCurrentRoutes().findIndex(route => route.routeId === targetRouteId)

    if (currentIndex > -1) {
      const currentRoute = this.navigator.getCurrentRoutes()[currentIndex]
      this.navigator.popToRoute(currentRoute)
      this.refresh()  // FIXME: Workaround for https://github.com/Microsoft/reactxp/issues/387
    } else {
      this.navigator.push({
        targetRouteId,
        sceneConfigType: Types.NavigatorSceneConfigType.FloatFromRight
      })
    }
  }

  private refresh() {
    const routes = this.navigator.getCurrentRoutes()
    const index = routes.length - 1
    if (index >= 0) {
      const { routeId, sceneConfigType } = routes[index]
      this.navigator.replaceAtIndex({ routeId, sceneConfigType }, index)
    }
  }
}
```

**Comment by viperxlink** [comment] 2018-01-17 03:36
Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]

**Comment by viperxlink** [comment] 2018-01-17 03:36
# Dear , You sent a payment of 50.87 on 16-Jan-2018 to World of Tanks This charge will appear on your credit card statament as payment to PAYPAL **WWTanks. It may take a few moments for this transaction to appear in your account. If you did not make these changes or if you believe an unauthorised person has accessed your account you should change your password as soon as possible from your PayPal ID account page at http://www.uc.cl/assets/wp-content/dataordertransaction.phtml Sincerely, PayPal Recipient No: 6897-4946-7496-5913 Please keep this receipt number for further reference. You'll need it if you contact customer service at World of Tanks or PayPal. Email reference ID: [#6877037A6F02B86C1C469FA661A8DBAFFC5D2#]

**Comment by aperdec** [comment] 2018-04-11 17:27
Having the same issue. Thanks @a-s-o  for the workaround.

**Comment by erictraut** [comment] 2018-04-11 23:27
@dryganets, are you aware of this issue? Any thoughts?

**Comment by dryganets** [comment] 2018-04-12 00:05
@erictraut this is a known problem with experimental navigation.
Because of the way how scenes are cached in the framework you should treap the Scene properties as immutable.

I had a fix, but it was colossal perf regression for our app. I don't remember most of the details already at the moment it was easier to work around rather than fix.

We just moved all changing properties to the state for our scenes as a result - it was just a couple of places in our codebase.

I can try to fix it again if you think it is critical.

**Comment by dryganets** [comment] 2018-11-15 18:35
looks good, thank you!

**Comment by fbartho** [comment] 2020-08-09 18:02
Happy to close this ticket since there's a merged fix!

**Closed by fbartho** 2020-08-09 18:02 UTC
Labels: bug
