### ISSUE TITLE
reactxp-navigation : immediatelyResetRouteStack/popToTop on Web

### ISSUE THREAD

**Issue by omatrot** [Microsoft/reactxp#344] opened 2017-11-05 09:25 UTC
I'm using the TodoList sample as the starting point of a new project.
I've added more routes to the navigator in order to build a wizard.

I've noticed that, on the Web only, when you've pushed more than 2 routes on the stack, immediatelyResetRouteStack works but the "view" is simply not visible on Web, iOS and Android are fine.

On the web you end up with a view where everything seems hidden. After checking DOM elements are here though.

If you navigate back (pop) each route, it is OK. Popping to top ends with the same problem.

**Comment by a-s-o** [comment] 2017-12-14 17:14
Hello, I am also having the same issue. There is a blank screen after call to immediatelyResetRouteStack() and no log output. I have only tested on he web so far.

Thank you; very happy with this framework so far. Thank you for providing it.

**Comment by erictraut** [comment] 2018-04-09 23:31
@dryganets, looks like a problem with the reactxp-navigation extension. Any thoughts on this one?

**Comment by dryganets** [comment] 2018-04-10 01:33
Looks like it is. I never touched web implementation. Will take a look, sounds like something easy to reproduce. If someone could share his already not working sample that would help :)

**Comment by erictraut** [comment] 2018-04-10 01:34
I think you can repro the problem with the unmodified TodoList sample.

**Comment by dryganets** [comment] 2018-04-10 21:29
@erictraut the problem is fixed in this PR:
https://github.com/Microsoft/reactxp/pull/590

We didn't reset some of the properties correctly and didn't have enableScene called on the stack reset.

**Closed** 2018-04-10 23:44 UTC
Labels: bug
